export type { Comparison } from './comparison'
export { eq, KIND as KIND_EQ } from './eq'
export { ge, KIND as KIND_GE } from './ge'
export { gt, KIND as KIND_GT } from './gt'
export { In, KIND as KIND_IN } from './in'
export { KIND as KIND_LE, le } from './le'
export { KIND as KIND_LT, lt } from './lt'
export { KIND as KIND_NE, ne } from './ne'
export { KIND as KIND_NOT_IN, notIn } from './not-in'
export { KIND as KIND_OVERLAP, overlap } from './overlap'
export { KIND as KIND_PREFIX, prefix } from './prefix'
export { KIND as KIND_PRESENT, present } from './present'
export { KIND as KIND_SUFFIX, suffix } from './suffix'
export { KIND as KIND_UNDEF, undef } from './undef'
