name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    container:
      image: node:20-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install npm modules
        run: yarn
      - name: Scan project for vulnerabilities
        run: yarn audit
      - name: Check licenses
        run: yarn check-licenses
      - name: Run test suite
        run: yarn test
      - name: Run build
        run: yarn build
